# Automatically generated by configure - do not modify
prefix=
bindir=
mandir=
datadir=
docdir=
MAKE=make
CC=gcc
HOST_CC=gcc
AR=ar
STRIP=strip -s -R .comment -R .note
CFLAGS=-O2
LDFLAGS=
EXESUF=
ARCH=i386
KERNEL_PATH=/lib/modules/2.6.23.12/build
CONFIG_KBUILD26=yes
SRC_PATH=/home/mru/dev/atmega_usb/kernel
